// flow-typed signature: d8d3fd92400ef3041d0645f7f6124445
// flow-typed version: <<STUB>>/hunspell-spellchecker_v^1.0.2/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hunspell-spellchecker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hunspell-spellchecker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hunspell-spellchecker/bin/hunspell-tojson' {
  declare module.exports: any;
}

declare module 'hunspell-spellchecker/gulpfile' {
  declare module.exports: any;
}

declare module 'hunspell-spellchecker/lib/dictionary' {
  declare module.exports: any;
}

declare module 'hunspell-spellchecker/lib/index' {
  declare module.exports: any;
}

declare module 'hunspell-spellchecker/test/check' {
  declare module.exports: any;
}

declare module 'hunspell-spellchecker/test/dictionary' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hunspell-spellchecker/bin/hunspell-tojson.js' {
  declare module.exports: $Exports<'hunspell-spellchecker/bin/hunspell-tojson'>;
}
declare module 'hunspell-spellchecker/gulpfile.js' {
  declare module.exports: $Exports<'hunspell-spellchecker/gulpfile'>;
}
declare module 'hunspell-spellchecker/lib/dictionary.js' {
  declare module.exports: $Exports<'hunspell-spellchecker/lib/dictionary'>;
}
declare module 'hunspell-spellchecker/lib/index.js' {
  declare module.exports: $Exports<'hunspell-spellchecker/lib/index'>;
}
declare module 'hunspell-spellchecker/test/check.js' {
  declare module.exports: $Exports<'hunspell-spellchecker/test/check'>;
}
declare module 'hunspell-spellchecker/test/dictionary.js' {
  declare module.exports: $Exports<'hunspell-spellchecker/test/dictionary'>;
}
